/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_KnnQuery */

#ifndef _Included_com_metisx_xvector_KnnQuery
#define _Included_com_metisx_xvector_KnnQuery
#ifdef __cplusplus
extern "C" {
#endif
#undef com_metisx_xvector_KnnQuery_TARGET_VECTOR_ARRAY
#define com_metisx_xvector_KnnQuery_TARGET_VECTOR_ARRAY 0L
#undef com_metisx_xvector_KnnQuery_TARGET_INDEX_ARRAY
#define com_metisx_xvector_KnnQuery_TARGET_INDEX_ARRAY 1L
/*
 * Class:     com_metisx_xvector_KnnQuery
 * Method:    nativeInit
 * Signature: (JI[FII)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_KnnQuery_nativeInit
  (JNIEnv *, jobject, jlong, jint, jfloatArray, jint, jint);

/*
 * Class:     com_metisx_xvector_KnnQuery
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_KnnQuery_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_KnnQuery
 * Method:    nativeSetTargets
 * Signature: (JI[J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_KnnQuery_nativeSetTargets
  (JNIEnv *, jobject, jlong, jint, jlongArray);

/*
 * Class:     com_metisx_xvector_KnnQuery
 * Method:    nativeSetFilters
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_KnnQuery_nativeSetFilters
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     com_metisx_xvector_KnnQuery
 * Method:    nativeGetResults
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_KnnQuery_nativeGetResults
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
