/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_IndexArray */

#ifndef _Included_com_metisx_xvector_IndexArray
#define _Included_com_metisx_xvector_IndexArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_IndexArray
 * Method:    nativeInit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_IndexArray_nativeInit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_IndexArray
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_IndexArray_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_IndexArray
 * Method:    nativeSetBuffer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_IndexArray_nativeSetBuffer
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_metisx_xvector_IndexArray
 * Method:    nativeGetLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_metisx_xvector_IndexArray_nativeGetLength
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
