/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_Buffer */

#ifndef _Included_com_metisx_xvector_Buffer
#define _Included_com_metisx_xvector_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeInit
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_Buffer_nativeInit
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCapacity
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_Buffer_nativeCapacity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[BJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3BJJ
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[CJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3CJJ
  (JNIEnv *, jobject, jlong, jcharArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[SJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3SJJ
  (JNIEnv *, jobject, jlong, jshortArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[IJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3IJJ
  (JNIEnv *, jobject, jlong, jintArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[JJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3JJJ
  (JNIEnv *, jobject, jlong, jlongArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[FJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3FJJ
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyHostToBuffer
 * Signature: (J[DJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyHostToBuffer__J_3DJJ
  (JNIEnv *, jobject, jlong, jdoubleArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[BJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3BJJ
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[CJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3CJJ
  (JNIEnv *, jobject, jlong, jcharArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[SJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3SJJ
  (JNIEnv *, jobject, jlong, jshortArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[IJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3IJJ
  (JNIEnv *, jobject, jlong, jintArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[JJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3JJJ
  (JNIEnv *, jobject, jlong, jlongArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[FJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3FJJ
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     com_metisx_xvector_Buffer
 * Method:    nativeCopyBufferToHost
 * Signature: (J[DJJ)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Buffer_nativeCopyBufferToHost__J_3DJJ
  (JNIEnv *, jobject, jlong, jdoubleArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
