/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_Filter */

#ifndef _Included_com_metisx_xvector_Filter
#define _Included_com_metisx_xvector_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_Filter
 * Method:    nativeInit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_Filter_nativeInit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_Filter
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Filter_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_Filter
 * Method:    nativeSetBuffer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Filter_nativeSetBuffer
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
