/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_Query */

#ifndef _Included_com_metisx_xvector_Query
#define _Included_com_metisx_xvector_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_Query
 * Method:    nativeExecute
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Query_nativeExecute
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
