/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_Context */

#ifndef _Included_com_metisx_xvector_Context
#define _Included_com_metisx_xvector_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_Context
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_Context_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_metisx_xvector_Context
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_Context_nativeClose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
