/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_VectorArray */

#ifndef _Included_com_metisx_xvector_VectorArray
#define _Included_com_metisx_xvector_VectorArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_VectorArray
 * Method:    nativeInit
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_metisx_xvector_VectorArray_nativeInit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_metisx_xvector_VectorArray
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_VectorArray_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_VectorArray
 * Method:    nativeDimension
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_metisx_xvector_VectorArray_nativeDimension
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_VectorArray
 * Method:    nativeSetBuffer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_VectorArray_nativeSetBuffer
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
