/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metisx_xvector_KnnResult */

#ifndef _Included_com_metisx_xvector_KnnResult
#define _Included_com_metisx_xvector_KnnResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metisx_xvector_KnnResult
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_metisx_xvector_KnnResult_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_KnnResult
 * Method:    nativeGetK
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_metisx_xvector_KnnResult_nativeGetK
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_KnnResult
 * Method:    nativeGetScores
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_metisx_xvector_KnnResult_nativeGetScores
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_KnnResult
 * Method:    nativeGetIndices
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_metisx_xvector_KnnResult_nativeGetIndices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_metisx_xvector_KnnResult
 * Method:    nativeVectorArrays
 * Signature: (J)[Lcom/metisx/xvector/VectorArray;
 */
JNIEXPORT jobjectArray JNICALL Java_com_metisx_xvector_KnnResult_nativeVectorArrays
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
