#ifndef __XVEC_STATUS_H__
#define __XVEC_STATUS_H__

#include <stdint.h>

extern "C"
{
    enum xvecStatus
    {
        XVEC_STATUS_SUCCESS,
        XVEC_STATUS_UNKNOWN,
        XVEC_STATUS_UNSUPPORTED_DATATYPE,
        XVEC_STATUS_OUT_OF_MEMORY,
        XVEC_STATUS_INVALID_PTR,
        XVEC_STATUS_INVALID_VECTOR_OBJ,
        XVEC_STATUS_INVALID_VECTOR_DIMENSION,
        XVEC_STATUS_INVALID_TYPE,
        XVEC_STATUS_INVALID_PARAMETER,
    };
}

#endif  // __XVEC_STATUS_H__